### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by Kateriine** [WFTDA/bouttime#138]
```
- Operating System Mac OS X 10.11.6
- Node Version v0.10.36
```

Might be a bug in node version: install ends with 

```
npm ERR! cb() never called!
npm ERR! not ok code 0
```

**Comment by kweerious** [comment]
Could you include more information?
Like which command you ran?
Did you run the `setup.sh` first?

**Comment by Kateriine** [comment]
Oops sorry - I just used `npm install -g wftda-bouttime`

**Comment by kweerious** [comment]
Ah thanks, we'll look into that. For now though, we are encouraging local dev installs (see https://github.com/WFTDA/bouttime#development).

**Comment by Kateriine** [comment]
Ok thanks :)

**Comment by kweerious** [comment]
@miketheman Looks like CircleCi is passing, but it's using a git checkout and npm install from local. Do you think we should have another build that tests npm installs? I'm wondering how much to rely on NPM really.

**Comment by miketheman** [comment]
@kweerious I think that eventually we will want npm to be a primary distribution of a completed artifact of this codebase, as it should not contain tests and dev dependencies.

In my mind, the project is still not mature enough to be on npm as an install method, other than reserving the namespace for future releases.

Our docs mention `npm install -g wftda-bouttime` - we could yank that from the docs until a time at which we are confident in npm as a distribution method.

Is your concern about relying on npm now, or in general for the future?

**Comment by kweerious** [comment]
@miketheman I'm good with moving the npm install method to the background until we get a production release. My question was more about wanting to test what we use, so we can re-visit the CircleCi using the npm registry later.

**Comment by miketheman** [comment]
@kweerious that makes more sense now. I see a future where we have an integration test suite, apart from the main codebase, that does the more intense, slow operations against browser types, and that would be the right place to install from NPM directly. 
Since the majority if the time we'd like to catch regression before release, some thought should go into how that is accomplished.

**Comment by RawnBear** [comment]
I've just tried to install/run after following the instructions for setting up a local dev environment by running setup.sh and then trying to run the server. I'm getting the following error:

module.js:340
    throw err;
          ^
Error: Cannot find module '../dist/server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/RawnBear/Desktop/bouttime-master/bin/bouttime-server:2:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

I'm completely new to Node so it's entirely possible I messed up the Node installation so I'll start over with that, but just curious if anyone else has seen this error or has any ideas what else I can do to get it going?

**Comment by RawnBear** [comment]
**Disclaimer in case you got an email notification about a comment that no longer exists:** I posted a comment earlier about an error I was encountering when trying to run the server after using setup.sh to install it, but deleted it because I realised I was probably doing something silly and wanted to try a few more things before asking for help.

Anyway I'm posting now because I've fixed my issue but wanted to provide some feedback on the local development environment instructions:

The problem I encountered was due to not actually _compiling_ the code, which may seem silly but I come from a web dev background so I'm not used to this :P 

I feel it would be useful to perhaps add a line explaining that gulp watch (or whatever the standard gulp compile command is) **must** to be run prior to trying to run the server. I misunderstood the line 

> gulp watch will automatically recompile assets when source files are changed

and thought it was only relevant if I was trying to edit source files on the fly, so I skipped it and went straight to trying to run the server. I see now this was a silly mistake but I tripped up on it and others might too. Just a thought :)
